account/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(
                           regex=r'^login/$',
                           view='django.contrib.auth.views.login',
                           kwargs={'template_name': 'account/login.html'},
                           name='login'
                       ),

                       url(
                           regex=r'^logout/$',
                           view='django.contrib.auth.views.logout',
                           kwargs={'next_page': 'account:login'},
                           name='logout'
                       ),

                       )

info/urls.py
from django.conf.urls import patterns, url
from .views import DetailListView

urlpatterns = patterns('',
                       url(r'^$', 'info.views.home', name='home'),
                       url(r'^view-detail/(?P<detail_id>\d+)/$', 'info.views.view_detail', name='view_detail'),
                       url(r'^detail-list/$', DetailListView.as_view()),
                       )

yougotagift/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views as rest_views


urlpatterns = patterns('',
                       url(r'^api-token-auth/', rest_views.obtain_auth_token),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^info/', include('info.urls', namespace='info')),
                       url(r'^account/', include('account.urls', namespace='account')),
                       )

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    create_dt = models.DateTimeField(auto_now_add=True)
    update_dt = models.DateTimeField(auto_now=True)
    delete_dt = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True

info/models.py
from django.db import models
from core.models import TimeStampedModel


class Detail(TimeStampedModel):
    name = models.CharField(max_length=128)

    def __unicode__(self):
        return self.name

info/forms.py
from django import forms
from info.models import Detail


class DetailForm(forms.ModelForm):
    class Meta:
        model = Detail
        fields = ['name', ]

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name'}),
        }

account/views.py
from django.shortcuts import render

# Create your views here.

info/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from rest_framework.authentication import TokenAuthentication, BasicAuthentication
from rest_framework.authtoken.models import Token
from core.shortcuts import reverse_redirect, get_object_or_None

from info.forms import DetailForm
from info.models import Detail
from info.serializers import DetailSerializer

from rest_framework import authentication
from rest_framework.decorators import api_view, authentication_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView


@login_required(login_url='/account/login/')
def home(request):
    args = {}

    if request.user:
        user = request.user
        token = Token.objects.get_or_create(user=user)
        args["token"] = token[0]

    if request.method == 'POST':
        form = DetailForm(request.POST)
        if form.is_valid():
            detail = form.save()
            messages.success(request, "Data successfully saved.")
            return reverse_redirect('info:view_detail', args=[detail.pk])

    else:
        form = DetailForm()

    args['form'] = form
    return render(request, 'info/home.html', args)


def view_detail(request, detail_id):
    args = {}
    detail = get_object_or_None(Detail, pk=detail_id, is_active=True)

    if detail:
        args["detail"] = detail
        return render(request, 'info/view_detail.html', args)
    else:
        messages.warning(request, "unable to locate detail")
        return reverse_redirect('info:home')


class JSONResponse(HttpResponse):

    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)


class DetailListView(APIView):
    authentication_classes = (TokenAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)

    def get(self, request, format=None):
        details = Detail.objects.all()
        serializer = DetailSerializer(details, many=True)
        return Response(serializer.data)

info/templates/info/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load core_extras %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <form method="post" action="{% url 'info:home' %}" style="width:80%;">
                {% csrf_token %}
                {% if form.non_field_errors %}
                    {% for key, value in form.non_field_errors.items %}
                        {% for error in value %}
                             {{ error }}
                        {% endfor %}
                    {% endfor %}
                {% endif %}

                {% for field in form %}
                    {{ field.label }}
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}
                    {{ field|addcss:"form-control" }}
                {% endfor %}
                <br />
                <button type="submit" class="btn btn-success btn-sm"> <i class="fa fa-floppy-o"></i> Save</button>
            </form>
        </div>


        <div class="col-sm-6">
            <table id="detailsTable" style="width:80%; margin-top:20px;" class="table table-condensed table-striped table-hover">

            </table>
        </div>
    </div>
</div>


<script>
    $(document).ready(function(){
        var user_url = 'http://localhost:8000/info/detail-list'
        var auth_headers = {
            Authorization: 'Token ' + '{{ token }}'
        }
        var validate_user = {
          url : user_url,
          dataType : 'json',
          headers: auth_headers,
          success : function(data) {
            console.log('authorized user returned');
            createTable(data);
          },
          error: function(XMLHttpRequest, textStatus, errorThrown) {
            console.log('error returned from ' + user_url);
          }
        };

        $.ajax(
          validate_user
        );

        function createTable(data){
            var content = '';

            $.each(data, function(i, item){
                console.log(data[i]);
                content += '<tr><td>' + data[i].name + '</td>' + '<td>' + data[i].create_dt + '</td></tr>';
            });

            $("#detailsTable").append(content);

        }


    });
</script>
{% endblock %}

info/templates/info/view_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load core_extras %}

{% block content %}

<div class="container">
    <div class="row">
    <h3>Hello {{ detail.name }}!</h3>


    </div>
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="container">
	<div class="row">
		<div class="pull-right" >
			<a href="{% url 'info:home' %}">Home</a> |
			{% if request.user.is_authenticated %}<a href="{% url 'account:logout' %}">Logout </a> {% endif %}

		</div>
		<hr />
		<div class="small-12 columns">
	    {% block messages %}
	        {% if messages %}
	            <div>
		            <ul class='messages'>
		            {% for message in messages %}
		                <li{% if message.tags %} class="{{message.tags}} message_item" {% endif %}>{{ message }}</li>
		            {% endfor %}
		            </ul>
	            </div>
	        {% endif %}

	    {% endblock %}
    	</div><!--./small-12-->
 	</div><!--./row-->

    </div>

    <section class="large-12 columns content" style='padding: 30px;'>
	    {% block content %}

	    {% endblock %}
	</section>


</body>
</html>